### ISSUE TITLE
CRUD operation

### ISSUE THREAD

**Issue by sankhakarfa** [solkin/minion-android#1]
Please add option to update a key value.

**Comment by solkin** [comment]
Sorry for this delay. 
As I understand, you mean to add such option for `IniRecord` object?
Will add it soon.

**Comment by solkin** [comment]
@sankhakarfa Please, update Minion dependency to version `1.0.2`.
Now, you can set record value by two ways. 
From Minion:
`minion.setValue("music", "genres", "Classical", "Lounge");`
or directly for IniRecord:
`iniRecord.setValue("Classical", "Lounge");`
